spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: kanav
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/